name = "test4_2"
display_name = "解毒;全体毒"
skill_type = "special"

[container]
selectors = [
    "caster",
    "ally_all",
    "enemy_all",
]


[[container.effect_config]]
name = "解除中毒补偿生命调整"
caster = 0
targets = 1
later_targets = 0
value = 0


[[container.effect_config]]
name = "中毒"
caster = 0
targets = 2
value = 3
duration = 3